### PR TITLE
Denno Louis and Oliver McLaughlin testimonial

### PR DESCRIPTION
**Pull request by olwmc**
This PR completes the assignment from last thursday, adding both Denno and my own testimonial and advice.

### CODE REVIEW

**Comment by brownsarahm** [comment]
If either of you would like to be credited for your comment replace `-- sp 22 student` with your name

**Comment by olwmc** [comment]
Is that required? @brownsarahm

**Comment by brownsarahm** [comment]
nope, it can stay how it is, or you can change it.

**Comment by brownsarahm** [comment]
I'm going to merge, you can take credit later if you like.

**Pull request merged**
